"use client";

import { useState } from "react";
import { Github, Plus, Trash2, X } from "lucide-react";
import type { GitHubRepository } from "@/lib/types";

export function RepositorySetup({ repositories, onClose, onAdd, onDelete }: { repositories: GitHubRepository[]; onClose: () => void; onAdd: (repository: Omit<GitHubRepository, "id">) => Promise<void>; onDelete: (id: string) => Promise<void> }) {
  const [owner, setOwner] = useState(""); const [name, setName] = useState(""); const [branch, setBranch] = useState("main"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const add = async () => { setBusy(true); setError(""); try { await onAdd({ owner: owner.trim(), name: name.trim(), defaultBranch: branch.trim() || "main" }); setOwner(""); setName(""); setBranch("main"); } catch { setError("Could not add this repository. It may already exist."); } finally { setBusy(false); } };
  return <div className="modal-backdrop" onMouseDown={onClose} role="presentation"><section className="repository-modal" role="dialog" aria-modal="true" aria-labelledby="repositories-title" onMouseDown={(event) => event.stopPropagation()}><div className="modal-header"><div><p className="eyebrow">Workspace</p><h2 id="repositories-title">GitHub repositories</h2><p>Register the repositories that tickets and agents can use.</p></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={19}/></button></div><div className="repository-form"><label>Owner or organization<input value={owner} onChange={(event) => setOwner(event.target.value)} placeholder="acme"/></label><label>Repository<input value={name} onChange={(event) => setName(event.target.value)} placeholder="product-app"/></label><label>Default branch<input value={branch} onChange={(event) => setBranch(event.target.value)} placeholder="main"/></label><button className="button primary" disabled={busy || !owner.trim() || !name.trim()} onClick={() => void add()}><Plus size={16}/>{busy ? "Adding…" : "Add repository"}</button></div>{error && <div className="auth-error">{error}</div>}<div className="repository-list">{repositories.length ? repositories.map((repository) => <div key={repository.id}><span className="repo-icon"><Github size={17}/></span><div><strong>{repository.owner}/{repository.name}</strong><small>Default branch: {repository.defaultBranch}</small></div><button onClick={() => void onDelete(repository.id)} aria-label={`Remove ${repository.owner}/${repository.name}`}><Trash2 size={16}/></button></div>) : <p>No repositories added yet.</p>}</div></section></div>;
}
