"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { answerAgentQuestion, addTicketComment, loadTicketCollaboration, reviewTicketProposal, submitHumanInput } from "@/lib/collaboration-store";
import type { Ticket } from "@/lib/types";
import type { AgentQuestion, HumanInputRequest, TicketComment, TicketProposal } from "@/lib/collaboration-types";
import { X } from "lucide-react";

export function TicketCollaboration({ ticket, onClose }: { ticket: Ticket; onClose: () => void }) {
  const [comments, setComments] = useState<TicketComment[]>([]); const [questions, setQuestions] = useState<AgentQuestion[]>([]); const [proposals, setProposals] = useState<TicketProposal[]>([]);
  const [inputRequests, setInputRequests] = useState<HumanInputRequest[]>([]);
  const [body, setBody] = useState(""); const [answers, setAnswers] = useState<Record<string, string>>({}); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submissionKeys = useRef<Record<string, string>>({});
  const refresh = useCallback(() => loadTicketCollaboration(ticket.id).then((value) => { setComments(value.comments); setQuestions(value.questions); setProposals(value.proposals); setInputRequests(value.inputRequests); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Could not load the conversation.")), [ticket.id]);
  useEffect(() => { void refresh(); }, [refresh]);
  const post = async () => { if (!body.trim()) return; setBusy(true); try { await addTicketComment(ticket.id, body); setBody(""); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not post the comment."); } finally { setBusy(false); } };
  const resolve = async (question: AgentQuestion) => { const answer = answers[question.id]?.trim(); if (!answer) return; setBusy(true); try { await answerAgentQuestion(question.id, answer); setAnswers((current) => ({ ...current, [question.id]: "" })); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not resolve the question."); } finally { setBusy(false); } };
  const submitRequest = async (request: HumanInputRequest) => { if (!request.questions.every((item) => answers[item.id]?.trim())) return; setBusy(true); const submissionKey = submissionKeys.current[request.id] ??= crypto.randomUUID(); try { await submitHumanInput(request.id, submissionKey, request.questions.map((item) => ({ questionId: item.id, answer: answers[item.id].trim() }))); delete submissionKeys.current[request.id]; await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not submit the answers."); } finally { setBusy(false); } };
  const review = async (proposal: TicketProposal, status: "approved" | "rejected") => { setBusy(true); try { await reviewTicketProposal(proposal.id, status); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not review the proposal."); } finally { setBusy(false); } };
  return <div className="modal-backdrop" onMouseDown={onClose} role="presentation"><section className="modal collaboration-modal" role="dialog" aria-modal="true" aria-labelledby="conversation-title" onMouseDown={(event) => event.stopPropagation()}>
    <div className="modal-header"><div><p className="eyebrow">Ticket conversation</p><h2 id="conversation-title">{ticket.title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={19}/></button></div>
    {error && <div className="error-banner">{error}</div>}
    {inputRequests.filter((item) => item.status === "active" || item.status === "blocked").map((request) => <div className="collaboration-question" key={request.id}><strong>{request.status === "blocked" ? "Agent blocked after too many clarification rounds" : `Agent needs input · round ${request.round}`}</strong>{request.questions.map((question) => <label key={question.id}><span>{question.prompt}</span>{question.type === "yes_no" || question.type === "single_choice" ? <select disabled={request.status === "blocked"} value={answers[question.id] ?? ""} onChange={(event) => setAnswers((current) => ({ ...current, [question.id]: event.target.value }))}><option value="">Choose…</option>{(question.type === "yes_no" ? ["Yes","No"] : question.options).map((option) => <option key={option}>{option}</option>)}</select> : <input disabled={request.status === "blocked"} value={answers[question.id] ?? ""} onChange={(event) => setAnswers((current) => ({ ...current, [question.id]: event.target.value }))} placeholder="Answer the agent…"/>}</label>)}{request.status === "active" && <button className="button primary" disabled={busy || !request.questions.every((item) => answers[item.id]?.trim())} onClick={() => void submitRequest(request)}>Submit answers and resume</button>}</div>)}
    {questions.filter((item) => item.status === "open" && !inputRequests.some((request) => request.questions.some((structured) => structured.prompt === item.question))).map((question) => <div className="collaboration-question" key={question.id}><strong>Agent question</strong><p>{question.question}</p><div className="inline-form"><input value={answers[question.id] ?? ""} onChange={(event) => setAnswers((current) => ({ ...current, [question.id]: event.target.value }))} placeholder="Answer the agent…"/><button className="button primary" disabled={busy || !answers[question.id]?.trim()} onClick={() => void resolve(question)}>Resolve</button></div></div>)}
    {proposals.filter((item) => item.status === "pending").map((proposal) => <div className="collaboration-proposal" key={proposal.id}><strong>Approval needed: {proposal.title}</strong><p>{proposal.description}</p><div className="form-actions"><button className="button secondary" disabled={busy} onClick={() => void review(proposal, "rejected")}>Reject</button><button className="button primary" disabled={busy} onClick={() => void review(proposal, "approved")}>Approve update</button></div></div>)}
    <div className="comment-list">{comments.length ? comments.map((comment) => <div className="comment" key={comment.id}><p>{comment.body}</p><small>{new Date(comment.createdAt).toLocaleString()}</small></div>) : <p className="empty-state">No comments yet. Start the conversation with the ticket owner or assignee.</p>}</div>
    <div className="comment-compose"><textarea rows={3} value={body} onChange={(event) => setBody(event.target.value)} placeholder="Write a comment…"/><button className="button primary" disabled={busy || !body.trim()} onClick={() => void post()}>Post comment</button></div>
  </section></div>;
}
